sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t omeraslam/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true omeraslam305/docker-react npm run test